---
title : "12.사용자정의 예외클래스 사용하기"
categories:
  - 파이썬(구조)
# tags:
#  - Python
#  - Python구조

date : 2020-11-29
---

필요한 경우 사용자정의 예외클래스를 만들어 사용할 수 있다. 그 방법에 대해 알아보자.  

raise 구문의 사용  
--- 

raise 구문 정의 : 사용자가 강제로 예외를 일으킬 때 사용하는 구문  
raise 구문 예시는 다음과 같다. 

```python  
def raiseErrorFunc():
    raise NameError      #Error는 발생하지 않았지만 Error가 발행한 것으로 동작하도록 함 


try:
    raiseErrorFunc()
except:
    print("NameError is Catched")


>>> Run module
NameError is Catched

```

사용자 정의 예외클래스 사용 
--- 

- 내장예외만으로는 한계가 있기때문에 사용자 정의예외를 정의하여 사용할 수 있다.  
- 예시는 다음과 같다.  

```python 
class NegativeDivisionError(Exception):   #Exception class를 상속받음 
    def __init__(self, value):            #생성자 method사용
        self.value = value


def positiveDivide(a, b):
    if(b < 0):                             #0보다 적은 경우 raise 구문으로 사용
        raise NegativeDivisionError(b)     #raise구문을 거치며 생성자에 b값을 보냄 (value=b)
    return a / b                           #b<0이 아니면 일반 연산 수행


try:
    ret = positiveDivide(10, -3)
    print('10 / 3 = {0}'.format(ret))
except NegativeDivisionError as e:        #NegativeDivisionError가 발생하면 e라는 인자이름으로 받아서 처리
    print('Error - Second argument of PositiveDivide is ', e.value)  #NegativeDivision Error의 value값을 출력
except ZeroDivisionError as e:
    print('Error - ', e.args[0])

>>>Run module
바Error - Second argument of PositiveDivide is  -3   #try 블럭에서 에러발생, 첫번째 except 구분에서 예외처리 발생

```
