---
title : "11.try except로 예외처리하기"
categories:
  - 파이썬(구조)
# tags:
#  - Python
#  - Python구조

date : 2020-11-29
---

운전을 할 때 가드레일이 있는 것 처럼 개발을 하면서도 안전장치가 필요하다.  
try except 구문을 통해 에러를 처리할 수 있는데 이 방법에 대해 알아보도록 하자.  


try except 구문 정의 및 사용방법  
---

- 실행시간(런타임)에 에러가 발생하여 코드가 중단되는 것을 방지할 때 사용하는 구문  
- 기본 형식은 아래와 같다.  

```python 
try : 
    <예외 발생 가능성이 있는 문장>     #예외가 발생하면 except로, 발생하지 않으면 else로 간다. 
except <예외종류>:                   #except는 여러개 가능 
    <예외처리 문장>
except (예외 1, 예외2):              #여러개를 튜플형식으로 넣을 수도 있음
    <예외처리 문장>
except 예외 as 인자:
    <예외처리 문장>
else:
    <예외가 발생하지 않은 경우 수행된 문장>
finally:
    <예외발생 유무에 상관없이 try 블록 이후 수행할 문장>
    
```

- 예시는 다음과 같다.  

```python 
def divide(a, b):
    return a / b

try:
    c = divide(5, 'string')
except ZeroDivisionError:
    print('두 번째 인자는 0이여서는 안됩니다.')
except TypeError:                  #이 경우 type error 형식으로 처리가 됨 
    print('모든 인자는 숫자여야 합니다.')
except:
    print('음 무슨 에러인지 모르겠음')
else:
    print('Result:{0}'.format(c))
finally:                           #Error 발생 여부와 상관없이 진행할 구문이 있다면 finally 구문을 추가한다.
    print('항상 finally 블럭은 수행됨')     
    
```
